### ISSUE TITLE
Deployment with S3 not working

### ISSUE THREAD

**Issue by HDGoldi** [QingWei-Li/notea#18]
Hi Everyone, 

maybe you can help me out. 
I am getting the following error:
```
[GET] /
12:15:28:97
2021-05-03T10:15:31.525Z	b8e0dad7-2d94-4da3-aa21-e9deb74a77e4	ERROR	AccessDenied: Access Denied
    at deserializeAws_restXmlGetObjectCommandError (/var/task/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js:6184:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /var/task/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
    at async /var/task/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
    at async StandardRetryStrategy.retry (/var/task/node_modules/@aws-sdk/middleware-retry/dist/cjs/defaultStrategy.js:56:46)
    at async /var/task/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    at async StoreS3.getObject (/var/task/.next/server/pages/index.js:2379:22)
    at async getSettings (/var/task/.next/server/pages/index.js:6795:44)
    at async handler (/var/task/.next/server/pages/index.js:2219:18)
    at async handler (/var/task/.next/server/pages/index.js:6896:17) {
  Code: 'AccessDenied',
  RequestId: '3CEDJNPHK28EFCD7',
  HostId: '9NjH40yi/f2xMWQIkGZuZ4WQ4pV44LIhoh7kQkmEk4NyirxORFh3TluTu17GhwrAUTmVci3PYGY=',
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 403,
    requestId: undefined,
    extendedRequestId: '9NjH40yi/f2xMWQIkGZuZ4WQ4pV44LIhoh7kQkmEk4NyirxORFh3TluTu17GhwrAUTmVci3PYGY=',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
RequestId: b8e0dad7-2d94-4da3-aa21-e9deb74a77e4 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

I have deployed notea via vercel.com. 

Here are my Environmental variables:
![image](https://user-images.githubusercontent.com/9448970/116865491-08aae500-ac0a-11eb-9440-9c9536796e6c.png)

The IAM Policy I am using is the following:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketTagging",
                "s3:GetObjectRetention",
                "s3:DeleteObjectVersion",
                "s3:GetBucketLogging",
                "s3:RestoreObject",
                "s3:ListBucket",
                "s3:GetBucketVersioning",
                "s3:GetBucketAcl",
                "s3:ReplicateObject",
                "s3:PutObject",
                "s3:GetObjectAcl",
                "s3:GetObject",
                "s3:GetEncryptionConfiguration",
                "s3:GetObjectTagging",
                "s3:DeleteObject",
                "s3:GetBucketLocation",
                "s3:PutBucketVersioning",
                "s3:ReplicateDelete",
                "s3:GetObjectVersion"
            ],
            "Resource": [
                "arn:aws:s3:::notea-jan-backend/*",
                "arn:aws:s3:::notea-jan-backend"
            ]
        }
```

Does anyone have an idea if I am missing some permission or what else the problem could be? 

Thanks a lot.

-Jan

**Comment by HDGoldi** [comment]
The problem is resolved! After redeploying it using the same credentials the problem was fone.
